### ISSUE TITLE
Error in readme examples: Missing () on function calls

### ISSUE THREAD

**Issue by AllenJB** [midorikocak/querymaker#1]
The readme examples are missing the brackets on function calls. As far as I can see there's no properties with the name `getQuery` / `getStatement` and no magic (`__get`/`__set`) that would make these work. As such a user will get an undefined property notice and NULL when trying to implement this library using the examples.

**Comment by midorikocak** [comment]
Thanks, fixing.

**Comment by midorikocak** [comment]
Fixed https://github.com/midorikocak/querymaker/commit/7edc3c48507e9c9918047e788f797b9cf00f0db7
